bot:
  name: Simba_pun_bot
  token: 6659689462:AAHYm1-uwB_2CFHNd2PgpIgWzGO1Wjapuiw
spring:
  datasource:
    url: jdbc:postgresql://193.124.45.147:5432/punbot_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect