name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Build and Deploy
        run: |
            mvn clean package
            mkdir -p $HOME/myapp
            cp target/*.jar $HOME/myapp/app.jar
            
            # Add SSH key to known_hosts
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            # SSH Deploy
            ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
              mkdir -p /myapp
              scp $HOME/myapp/app.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/myapp
              cd /myapp && java -jar app.jar
            "
