name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build with Maven
        run: | 
            mvn clean package
            mkdir -p $HOME/myapp
            cp target/TelegramBot-3.2.2.jar $HOME/myapp/app.jar

      - name: List target directory
        run: ls -l target

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            scp $HOME/myapp/app.jar user@remote:/myapp
            cd /myapp
            java -jar app.jar
