name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Build with Maven
        run: |
            mvn clean package
            
      - name: List target directory
        run: ls -l target

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path:  /home/runner/work/TelegramBot/TelegramBot/target/TelegramBot-3.2.2.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: myapp
          path: /home/runner/work/TelegramBot/TelegramBot/target/TelegramBot-3.2.2.jar
          
      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          
          
      - name: List downloaded artifacts
        run: ls -l $HOME/work/TelegramBot/TelegramBot/target/TelegramBot-3.2.2.jar
     
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy JAR to server
        run: |
          ls -l $HOME/work/TelegramBot/TelegramBot/target/TelegramBot-3.2.2.jar
          scp $HOME/work/TelegramBot/TelegramBot/target/TelegramBot-3.2.2.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home
    
